
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-stage

WORKDIR /rowmark-backend-build

COPY *.csproj ./
RUN dotnet restore

COPY . .

RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime-stage

WORKDIR /rowmark-backend

COPY --from=build-stage /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "rowmark.dll"]